baseURL = "https://www.rodolfocarvalho.net/"
languageCode = "en"
title = "Rodolfo Carvalho"

enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
home = ["HTML"]
page = ["HTML"]
section = ["HTML"]
