baseURL = "https://www.rodolfocarvalho.net/"
languageCode = "en"
title = "Rodolfo Carvalho"

enableRobotsTXT = true
disableAliases = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
home = ["HTML", "REDIRECTS"]
page = ["HTML"]
section = ["HTML"]

[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""
