[build]
publish = "public"
command = "hugo --minify"

[build.environment]
HUGO_VERSION = "0.54.0"

[context.deploy-preview]
command = "hugo --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --minify -b $DEPLOY_PRIME_URL"
